name: Create Artifact
description: Upload an artifact to S3.
inputs:
  artifact:
    description: The raw file contents.
    required: true
  aws-access-key-id:
    description: AWS access key ID.
    required: true
  aws-secret-access-key:
    description: AWS secret access key.
    required: true
  cache-control:
    description: HTTP cache control directive for the S3 object
    required: false
  public:
    description: Make this artifact public
    required: false
    default: 'false'
  s3-bucket-name:
    description: The name of the S3 bucket.
    required: true
  s3-object-key:
    description: The object key used to store the file in S3.
    required: true
outputs:
  success:
    description: The value will be 'true' if the operation succeeded, otherwise
      'false'.
runs:
  using: node16
  main: main.mjs
