name: CI
on:
  pull_request:
    paths-ignore:
      - .gitignore
      - .prettierignore
      - LICENSE
      - package.json
      - README.md
  push:
    branches:
      - main
    paths-ignore:
      - .gitignore
      - .prettierignore
      - LICENSE
      - package.json
      - README.md
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@v2
      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
      - name: Build package
        run: yarn build
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@v2
      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
      - name: Check code style
        run: yarn code:check
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit
        uses: actions/checkout@v2
      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
      - name: Run tests
        uses: ./.github/actions/jest
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          generate-artifacts: ${{ github.ref == 'refs/heads/main' }}
          s3-bucket-name: blvd-corp-github-ci-artifacts
          s3-object-path: ${{ github.repository }}/workflows/ci
